#!/bin/bash

cp ../moonjit/src/libluajit.so .
cp ../release/RosaServer/librosaserver.so .
cp ../release/RosaServerSatellite/rosaserversatellite .

taskset -c 0 ./start

rm -f ./server.srk
rm -f ./serverlog.txt