name: CMake

on: [push, pull_request]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    name: Build
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Checkout Submodules
      uses: textbook/git-checkout-submodule-action@2.1.1
    
    - name: Build moonjit
      shell: bash
      working-directory: ${{github.workspace}}/moonjit/src
      run: sudo make XCFLAGS+=-DLUAJIT_ENABLE_LUA52COMPAT
    
    - name: Create Build Environment
      run: cmake -E make_directory ${{github.workspace}}/release
    
    - name: Configure CMake
      shell: bash
      working-directory: ${{github.workspace}}/release
      env:
        CXX: g++-10
        CC: gcc-10
      run: cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE
    
    - name: Build
      working-directory: ${{github.workspace}}/release
      shell: bash
      run: cmake --build . --config $BUILD_TYPE
    
    - name: Test
      working-directory: ${{github.workspace}}/test
      shell: bash
      run: ./test
